### ISSUE TITLE
Uploading new images web error

### ISSUE THREAD

**Issue by PietroDG** [onesilop/territory.mobi#24]
![Upload error](https://user-images.githubusercontent.com/57643451/68652555-d45ae900-057d-11ea-9e1b-93a64bc07c1a.jpg)

This happens when saving a new uploaded image file..

**Comment by onesilop** [comment]
cant replicate the issue please try doing it again, as it may have been a transient issue.

**Comment by PietroDG** [comment]
It’s because you should try the “find new image” method not the previous ones. 
Make sure you try taking a photo, and or upload a new image to replicate the error, also try different browsers.
