### ISSUE TITLE
It’s because you should try the “find new image” method not the previous ones.

### ISSUE THREAD

**Issue by PietroDG** [onesilop/territory.mobi#25]
It’s because you should try the “find new image” method not the previous ones. 
Make sure you try taking a photo, and or upload a new image to replicate the error, also try different browsers.

_Originally posted by @PietroDG in https://github.com/onesilop/territory.mobi/issues/24#issuecomment-553126979_

**Comment by PietroDG** [comment]
Please don’t close an issue when it is still an issue. Bit presumptuous.

**Comment by a138768** [comment]
https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

I have tried to reproduce this issue multiple times and have not been able to. We only support chrome as a browser. Enjoy

**Comment by PietroDG** [comment]
Use the “find new image” then click on save. 
I do use chrome. 
And the error replicates every time. 

![image](https://user-images.githubusercontent.com/57643451/68715901-2429c680-05f7-11ea-81c2-bc0c2320e5bd.jpg)
